### ISSUE TITLE
ImageDream, AssertionError: xformers is not available

### ISSUE THREAD

**Issue by HigherOrderGames** [dreamgaussian/dreamgaussian#108]
I tried running the code on runpod.io using the runpod/pytorch:1.13.0-py3.10-cuda11.7.1-devel-ubuntu22.04 template.

I cloned the repository and followed the installation instructions.

I ran the provided command to use ImageDream:

```
python main.py --config configs/imagedream.yaml input=data/ghost_rgba.png prompt="a ghost eating hamburger" save_path=ghost
```

I got this error:

```
[INFO] load image from data/ghost_rgba.png...
Number of points at initialisation :  5000
[INFO] loading ImageDream...
Loading model from config: sd_v2_base_ipmv.yaml
Traceback (most recent call last):
  File "main.py", line 917, in <module>
    gui.train(opt.iters)
  File "main.py", line 891, in train
    self.prepare_train()
  File "main.py", line 145, in prepare_train
    self.guidance_sd = ImageDream(self.device)
  File "/workspace/dreamgaussian/guidance/imagedream_utils.py", line 27, in __init__
    self.model = build_model(self.model_name, ckpt_path=self.ckpt_path).eval().to(self.device)
  File "/usr/local/lib/python3.8/dist-packages/imagedream/model_zoo.py", line 53, in build_model
    model = instantiate_from_config(config.model)
  File "/usr/local/lib/python3.8/dist-packages/imagedream/ldm/util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/usr/local/lib/python3.8/dist-packages/imagedream/ldm/interface.py", line 47, in __init__
    unet = instantiate_from_config(unet_config)
  File "/usr/local/lib/python3.8/dist-packages/imagedream/ldm/util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/usr/local/lib/python3.8/dist-packages/imagedream/ldm/modules/diffusionmodules/openaimodel.py", line 696, in __init__
    else SpatialTransformer3D(
  File "/usr/local/lib/python3.8/dist-packages/imagedream/ldm/modules/attention.py", line 415, in __init__
    [
  File "/usr/local/lib/python3.8/dist-packages/imagedream/ldm/modules/attention.py", line 416, in <listcomp>
    BasicTransformerBlock3D(
  File "/usr/local/lib/python3.8/dist-packages/imagedream/ldm/modules/attention.py", line 242, in __init__
    assert XFORMERS_IS_AVAILBLE, "xformers is not available"
AssertionError: xformers is not available
```
How can I make it work?

**Comment by yangeer** [comment]
you can use this : pip install xformers
