### ISSUE TITLE
Can't save the model to geometry & Texture in stage 1

### ISSUE THREAD

**Issue by MrForExample** [dreamgaussian/dreamgaussian#117]
``` bash
C:\Users\reall\Softwares\Miniconda3\envs\AITexturing\Lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:3527.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Tensor occ torch.Size([128, 128, 128]) torch.float32 cuda:0 ∈ [0.0, 45.275028228759766] μ = 0.3088160753250122 σ = 1.5838950872421265
[INFO] mesh cleaning: (32370, 3) --> (18252, 3), (64720, 3) --> (36518, 3)
[INFO] marching cubes result: torch.Size([18252, 3]) (-0.6858707070350647-0.6744740009307861), torch.Size([36518, 3])
[INFO] unwrap uv...
Traceback (most recent call last):
  File "C:\Users\reall\Softwares\Miniconda3\envs\AITexturing\_Projects\dreamgaussian\main.py", line 691, in callback_save
    self.save_model(mode=user_data)
  File "C:\Users\reall\Softwares\Miniconda3\envs\AITexturing\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reall\Softwares\Miniconda3\envs\AITexturing\_Projects\dreamgaussian\main.py", line 436, in save_model
    glctx = dr.RasterizeGLContext()
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reall\Softwares\Miniconda3\envs\AITexturing\Lib\site-packages\nvdiffrast\torch\ops.py", line 221, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reall\Softwares\Miniconda3\envs\AITexturing\Lib\site-packages\nvdiffrast\torch\ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "C:\Users\reall\Softwares\Miniconda3\envs\AITexturing\Lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "C:\Users\reall\Softwares\Miniconda3\envs\AITexturing\Lib\site-packages\torch\utils\cpp_extension.py", line 1736, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reall\Softwares\Miniconda3\envs\AITexturing\Lib\site-packages\torch\utils\cpp_extension.py", line 2136, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing nvdiffrast_plugin_gl: The specified module could not be found.
```

**Comment by linnajing** [comment]
Hello. Is this problem solved?
