### ISSUE TITLE
Can not be training. CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by zhongqiu1245** [dreamgaussian/dreamgaussian#124]
Hello!
Thank you for your amazing job!
But, when I tried to reproduce your work, similar this issue https://github.com/dreamgaussian/dreamgaussian/issues/40, I met this error which blocked training:
```
python main.py --config configs/image.yaml input=data/test_rgba.png save_path=ckpt

/home/xxx/ProgramFiles/anaconda3/envs/dgs/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.
  warnings.warn(problem)
[INFO] load image from data/test_rgba.png...
Number of points at initialisation :  5000
[INFO] loading zero123...
Keyword arguments {'trust_remote_code': True} are not expected by Zero123Pipeline and will be ignored.
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 22.92it/s]
[INFO] loaded zero123!
  0%|                                                                                                         | 0/500 [00:00<?, ?it/s]

---------------------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/xxx/DATA/Processing/OFFICE/CodingFactory/PosWorkShop/dreamgaussian/main.py", line 917, in <module>
    gui.train(opt.iters)
  File "/media/xxx/DATA/Processing/OFFICE/CodingFactory/PosWorkShop/dreamgaussian/main.py", line 893, in train
    self.train_step()
  File "/media/xxx/DATA/Processing/OFFICE/CodingFactory/PosWorkShop/dreamgaussian/main.py", line 270, in train_step
    loss = loss + self.opt.lambda_zero123 * self.guidance_zero123.train_step(images, vers, hors, radii, step_ratio=step_ratio if self.opt.anneal_timestep else None, default_elevation=self.opt.elevation)
  File "/media/xxx/DATA/Processing/OFFICE/CodingFactory/PosWorkShop/dreamgaussian/guidance/zero123_utils.py", line 156, in train_step
    noise_pred = self.unet(
  File "/home/xxx/ProgramFiles/anaconda3/envs/dgs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/ProgramFiles/anaconda3/envs/dgs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/ProgramFiles/anaconda3/envs/dgs/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 1075, in forward
    sample, res_samples = downsample_block(
  File "/home/xxx/ProgramFiles/anaconda3/envs/dgs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/ProgramFiles/anaconda3/envs/dgs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/ProgramFiles/anaconda3/envs/dgs/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 1159, in forward
    hidden_states = resnet(hidden_states, temb, scale=lora_scale)
  File "/home/xxx/ProgramFiles/anaconda3/envs/dgs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/ProgramFiles/anaconda3/envs/dgs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/ProgramFiles/anaconda3/envs/dgs/lib/python3.10/site-packages/diffusers/models/resnet.py", line 764, in forward
    hidden_states = self.conv1(hidden_states, scale) if not USE_PEFT_BACKEND else self.conv1(hidden_states)
  File "/home/xxx/ProgramFiles/anaconda3/envs/dgs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/ProgramFiles/anaconda3/envs/dgs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/ProgramFiles/anaconda3/envs/dgs/lib/python3.10/site-packages/diffusers/models/lora.py", line 358, in forward
    return F.conv2d(
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
The environment is as same as `requirements.lock.txt`, each step is following `readme.md`, but this error came out.
I also tried install by  `requirements.txt`, same error...
I tested torch2.1 and cuda12.1, they worked normally. 
Could you tell me how to fix this?
Thank you in advance!

**Comment by zhongqiu1245** [comment]
ubuntu 22.04
python 3.10
others are as same as `requirements.lock.txt`
RTX 4060

**Comment by zhongqiu1245** [comment]
When I added `CUDA_LAUNCH_BLOCKING=1`, this error came out:
```
段错误 (核心已转储)
```
which makes me confuse...

**Comment by mayu-snba19** [comment]
I also struggled with the same error for several days.

In my case, after uninstalling the already installed `diff-gaussian-rasterization`, I modified the line around line 29 in the `setup.py` file within `diff-gaussian-rasterization` from:
```python
extra_compile_args={"nvcc": ["-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "third_party/glm/")]}
```
to:
```python
extra_compile_args={"nvcc": ["-Xcompiler", "-fno-gnu-unique", "-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "third_party/glm/")]}
```
After making this change, I reinstalled it using pip and was relieved from memory errors!

Reference: gaussian-splatting / RuntimeError: CUDA error: an illegal memory access was encountered
https://github.com/graphdeco-inria/gaussian-splatting/issues/41

Environment:
- Ubuntu 20.04
- Python 3.10
- RTX A4000
- CUDA 11.8
