### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by thegreatsai** [dreamgaussian/dreamgaussian#127]
I am running the installation on my local machine and got this error message below. The requirement installation went fine. What to do?

F:\StableDiffusion\dreamgaussian>pip install ./diff-gaussian-rasterization
Processing f:\stablediffusion\dreamgaussian\diff-gaussian-rasterization
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "F:\StableDiffusion\dreamgaussian\diff-gaussian-rasterization\setup.py", line 21, in <module>
          CUDAExtension(
        File "C:\Users\Opu\miniconda3\Lib\site-packages\torch\utils\cpp_extension.py", line 1074, in CUDAExtension
          library_dirs += library_paths(cuda=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Opu\miniconda3\Lib\site-packages\torch\utils\cpp_extension.py", line 1208, in library_paths
          paths.append(_join_cuda_home(lib_dir))
                       ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Opu\miniconda3\Lib\site-packages\torch\utils\cpp_extension.py", line 2407, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by shiboliu** [comment]
python=3.8

(dream) chian@chian:~/pyProjects/dreamgaussian$ pip install ./diff-gaussian-rasterization
Processing ./diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff-gaussian-rasterization
  Building wheel for diff-gaussian-rasterization (setup.py) ... done
  Created wheel for diff-gaussian-rasterization: filename=diff_gaussian_rasterization-0.0.0-cp38-cp38-linux_x86_64.whl size=3892675 sha256=6bd5d9afd3a2df4ba54dc03947f39528549ce6f07676e313e5b47eec8aea369a
  Stored in directory: /home/chian/.cache/pip/wheels/1a/5a/1c/4ff8ec546db95aee68f5769422cfeb07a6465d23ed79631ee5
Successfully built diff-gaussian-rasterization
Installing collected packages: diff-gaussian-rasterization
  Attempting uninstall: diff-gaussian-rasterization
    Found existing installation: diff-gaussian-rasterization 0.0.0
    Uninstalling diff-gaussian-rasterization-0.0.0:
      Successfully uninstalled diff-gaussian-rasterization-0.0.0
Successfully installed diff-gaussian-rasterization-0.0.0

**Comment by bingruihu** [comment]
the same question, did you solve it?

**Comment by hxj2580** [comment]
the same question, did you solve it?
