### ISSUE TITLE
Get the error: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.00 MiB. GPU 

### ISSUE THREAD

**Issue by wiktorkujawa** [dreamgaussian/dreamgaussian#142]
After running: 
`python -m kiui.cli.clip_sim data/test_rgba.png logs/test.obj`

```
in oss file
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.63s/it]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/wiktor/anaconda3/lib/python3.11/site-packages/kiui/cli/clip_sim.py", line 64, in <module>
    clip = CLIP('cuda', model_name='laion/CLIP-ViT-bigG-14-laion2B-39B-b160k')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wiktor/anaconda3/lib/python3.11/site-packages/kiui/cli/clip_sim.py", line 16, in __init__
    self.clip_model = CLIPModel.from_pretrained(model_name).to(self.device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wiktor/anaconda3/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2576, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wiktor/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/wiktor/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/home/wiktor/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/home/wiktor/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/home/wiktor/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/wiktor/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
           ^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.00 MiB. GPU 
```
My CUDA version is 12.1, NVidia driver 535, I am using Ubuntu 22.0.4

**Comment by hongyi-h** [comment]
This is because your GPU memory is limited. Try to change a GPU with more significant memory.
