### ISSUE TITLE
Missing mandatory value: $FULL_KEY"

### ISSUE THREAD

**Issue by yangqinhui0423** [dreamgaussian/dreamgaussian#151]
When I run "python main.py --config configs/image.yaml load=logs/name_model.ply gui=True" to visualize, I get error:
Number of points at loading :  28491
Traceback (most recent call last):
  File "main.py", line 913, in <module>
    gui = GUI(opt)
  File "main.py", line 84, in __init__
    self.register_dpg()
  File "main.py", line 719, in register_dpg
    default_value=self.opt.save_path,
  File "D:\anaconda3\envs\dream\lib\site-packages\omegaconf\dictconfig.py", line 359, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "D:\anaconda3\envs\dream\lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "D:\anaconda3\envs\dream\lib\site-packages\omegaconf\_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "D:\anaconda3\envs\dream\lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "D:\anaconda3\envs\dream\lib\site-packages\omegaconf\dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "D:\anaconda3\envs\dream\lib\site-packages\omegaconf\dictconfig.py", line 451, in _get_impl
    return self._resolve_with_default(
  File "D:\anaconda3\envs\dream\lib\site-packages\omegaconf\basecontainer.py", line 96, in _resolve_with_default
    raise MissingMandatoryValue("Missing mandatory value: $FULL_KEY")
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: save_path
    full_key: save_path
    object_type=dict

**Comment by wiktorkujawa** [comment]
You have the answer, actually: "Missing mandatory value: save_path". However, that script was probably broken from the start. As you have a GUI, but you can't do anything with that, and you get errors like: "AttributeError: 'int' object has no attribute 'backward'
python main.py --config configs/image.yaml load=logs/name_model.ply save_path=name gui=True

ps. I know that this repo has been abandoned for like two years, but I wanted to answer the question
