### ISSUE TITLE
pip install ./diff-gaussian-rasterization&pip install ./simple-knn error

### ISSUE THREAD

**Issue by DYJ-2000** [dreamgaussian/dreamgaussian#152]
### **1**
Looking in indexes: https://mirrors.ustc.edu.cn/pypi/web/simple
Processing d:\dreamgaussian\simple-knn
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\dreamgaussian\simple-knn\setup.py", line 13, in <module>
          from torch.utils.cpp_extension import CUDAExtension, BuildExtension
        File "C:\Users\13668\.conda\envs\DreamGaussian\lib\site-packages\torch\utils\cpp_extension.py", line 28, in <module>
          from pkg_resources import packaging  # type: ignore[attr-defined]
      ImportError: cannot import name 'packaging' from 'pkg_resources' (C:\Users\13668\.conda\envs\DreamGaussian\lib\site-packages\pkg_resources\__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### **2**
Looking in indexes: https://mirrors.ustc.edu.cn/pypi/web/simple
Processing d:\dreamgaussian\diff-gaussian-rasterization
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\dreamgaussian\diff-gaussian-rasterization\setup.py", line 13, in <module>
          from torch.utils.cpp_extension import CUDAExtension, BuildExtension
        File "C:\Users\13668\.conda\envs\DreamGaussian\lib\site-packages\torch\utils\cpp_extension.py", line 28, in <module>
          from pkg_resources import packaging  # type: ignore[attr-defined]
      ImportError: cannot import name 'packaging' from 'pkg_resources' (C:\Users\13668\.conda\envs\DreamGaussian\lib\site-packages\pkg_resources\__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I use conda to install then i cant solve this error,i try these also
python setup.py install  
new error
Traceback (most recent call last):
  File "D:\dreamgaussian\simple-knn\setup.py", line 13, in <module>
    from torch.utils.cpp_extension import CUDAExtension, BuildExtension
  File "C:\Users\13668\.conda\envs\DreamGaussian\lib\site-packages\torch\utils\cpp_extension.py", line 28, in <module>
    from pkg_resources import packaging  # type: ignore[attr-defined]
ImportError: cannot import name 'packaging' from 'pkg_resources' (C:\Users\13668\.conda\envs\DreamGaussian\lib\site-packages\pkg_resources\__init__.py)

this is my GPU
PyTorch version: 2.1.0
CUDA version: 12.1
CUDA available: True
CUDA device count: 1
Current CUDA device: 0
Device name: NVIDIA GeForce RTX 4060 Laptop GPU

these my pip list
Python 3.10.14

Package                   Version
------------------------- -------------
accelerate                0.30.1
aiofiles                  23.2.1
aiohttp                   3.9.5
aiosignal                 1.3.1
altair                    5.3.0
annotated-types           0.6.0
antlr4-python3-runtime    4.9.3
anyio                     4.3.0
async-timeout             4.0.3
asyncer                   0.0.7
attrs                     23.2.0
Brotli                    1.1.0
certifi                   2024.2.2
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
coloredlogs               15.0.1
contourpy                 1.2.1
cycler                    0.12.1
dataclasses-json          0.6.6
dearpygui                 1.11.1
Deprecated                1.2.14
diffusers                 0.27.2
dnspython                 2.6.1
einops                    0.8.0
email_validator           2.1.1
exceptiongroup            1.2.1
executing                 2.0.1
fastapi                   0.111.0
fastapi-cli               0.0.3
ffmpy                     0.3.2
filelock                  3.14.0
filetype                  1.2.0
flatbuffers               24.3.25
fonttools                 4.51.0
frozenlist                1.4.1
fsspec                    2024.5.0
ftfy                      6.2.0
gradio                    4.31.3
gradio_client             0.16.3
h11                       0.14.0
httpcore                  1.0.5
httptools                 0.6.1
httpx                     0.27.0
huggingface-hub           0.23.0
humanfriendly             10.0
idna                      3.7
imagedream                0.0.1
imageio                   2.34.1
imageio-ffmpeg            0.4.9
importlib_metadata        7.1.0
importlib_resources       6.4.0
Jinja2                    3.1.4
joblib                    1.4.2
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
kiui                      0.2.9
kiwisolver                1.4.5
lazy_loader               0.4
llvmlite                  0.42.0
markdown-it-py            3.0.0
MarkupSafe                2.1.5
marshmallow               3.21.2
matplotlib                3.9.0
mdurl                     0.1.2
mpmath                    1.3.0
msvc-runtime              14.34.31931
multidict                 6.0.5
mvdream                   0.0.1
mypy-extensions           1.0.0
networkx                  3.3
ninja                     1.11.1.1
numba                     0.59.1
numpy                     1.26.4
nvdiffrast                0.3.1
objprint                  0.2.3
omegaconf                 2.3.0
onnxruntime               1.17.3
onnxruntime-gpu           1.17.1
open-clip-torch           2.24.0
opencv-python             4.9.0.80
opencv-python-headless    4.9.0.80
orjson                    3.10.3
packaging                 24.0
pandas                    2.2.2
pillow                    10.3.0
pip                       24.0
platformdirs              4.2.2
plyfile                   1.0.3
pooch                     1.8.1
protobuf                  5.26.1
psutil                    5.9.8
pydantic                  2.7.1
pydantic_core             2.18.2
pydub                     0.25.1
pygltflib                 1.16.2
Pygments                  2.18.0
PyMatting                 1.1.12
PyMCubes                  0.1.4
pymeshlab                 2023.12.post1
pyparsing                 3.1.2
pyreadline3               3.4.1
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-multipart          0.0.9
pytz                      2024.1
PyYAML                    6.0.1
referencing               0.35.1
regex                     2024.5.15
rembg                     2.0.56
requests                  2.32.2
rich                      13.7.1
rpds-py                   0.18.1
ruff                      0.4.4
safetensors               0.4.3
scikit-image              0.23.2
scikit-learn              1.4.2
scipy                     1.13.0
semantic-version          2.10.0
sentencepiece             0.2.0
setuptools                70.0.0
shellingham               1.5.4
six                       1.16.0
sniffio                   1.3.1
starlette                 0.37.2
sympy                     1.12
threadpoolctl             3.5.0
tifffile                  2024.5.10
timm                      1.0.3
tokenizers                0.19.1
tomlkit                   0.12.0
toolz                     0.12.1
torch                     2.1.0
torchaudio                2.1.0
torchvision               0.16.0
tqdm                      4.66.4
transformers              4.40.2
trimesh                   4.3.2
typer                     0.12.3
typing_extensions         4.11.0
typing-inspect            0.9.0
tzdata                    2024.1
ujson                     5.10.0
urllib3                   2.2.1
uvicorn                   0.29.0
varname                   0.13.1
watchdog                  4.0.0
watchfiles                0.21.0
wcwidth                   0.2.13
websockets                11.0.3
wheel                     0.43.0
win-inet-pton             1.1.0
wrapt                     1.16.0
xatlas                    0.0.9
yarl                      1.9.4
zipp                      3.18.2

**Comment by DYJ-2000** [comment]
by the way my system is Win11

**Comment by TigerRaiders** [comment]
I also cannnot get it to work on my machine, also on windows 11. Would the issue be that its not working on windows 11?
