### ISSUE TITLE
RUNNing error on text-to-3D using MVdream

### ISSUE THREAD

**Issue by Unnnncode** [dreamgaussian/dreamgaussian#160]
When I run the codes followed readme.md , which is using MVdream：eg text-3D  & text+image-to-3D
`python main.py --config configs/text_mv.yaml prompt="a plush toy of a corgi nurse" save_path=corgi_nurse`
or
`python main.py --config configs/imagedream.yaml input=data/ghost_rgba.png prompt="a ghost eating hamburger" save_path=ghost`

Issues occur：
` File "/home/kemove/anaconda3/envs/dreamgs/lib/python3.9/site-packages/torch/nn/functional.py", line 5438, in multi_head_attention_forward
    raise RuntimeError(f"The shape of the 2D attn_mask is {attn_mask.shape}, but should be {correct_2d_size}.")
RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).
`
if its a Environmental error?
How can i solve it?
THX!

**Comment by Unnnncode** [comment]
Full errors record below:
`Traceback (most recent call last):
  File "/home/kemove/dianwang/dreamgaussian/main.py", line 917, in <module>
    gui.train(opt.iters)
  File "/home/kemove/dianwang/dreamgaussian/main.py", line 891, in train
    self.prepare_train()
  File "/home/kemove/dianwang/dreamgaussian/main.py", line 175, in prepare_train
    self.guidance_sd.get_image_text_embeds(self.input_img_torch, [self.prompt], [self.negative_prompt])
  File "/home/kemove/anaconda3/envs/dreamgs/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/kemove/dianwang/dreamgaussian/guidance/imagedream_utils.py", line 57, in get_image_text_embeds
    pos_embeds = self.encode_text(prompts).repeat(5,1,1)
  File "/home/kemove/dianwang/dreamgaussian/guidance/imagedream_utils.py", line 64, in encode_text
    embeddings = self.model.get_learned_conditioning(prompt).to(self.device)
  File "/home/kemove/anaconda3/envs/dreamgs/lib/python3.9/site-packages/imagedream/ldm/interface.py", line 177, in get_learned_conditioning
    return self.clip_model(prompts)
  File "/home/kemove/anaconda3/envs/dreamgs/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kemove/anaconda3/envs/dreamgs/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kemove/anaconda3/envs/dreamgs/lib/python3.9/site-packages/imagedream/ldm/modules/encoders/modules.py", line 218, in forward
    z = self.encode_with_transformer(tokens.to(self.device))
  File "/home/kemove/anaconda3/envs/dreamgs/lib/python3.9/site-packages/imagedream/ldm/modules/encoders/modules.py", line 282, in encode_with_transformer
    x = self.text_transformer_forward(x, attn_mask=self.model.attn_mask)
  File "/home/kemove/anaconda3/envs/dreamgs/lib/python3.9/site-packages/imagedream/ldm/modules/encoders/modules.py", line 297, in text_transformer_forward
    x = r(x, attn_mask=attn_mask)
  File "/home/kemove/anaconda3/envs/dreamgs/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kemove/anaconda3/envs/dreamgs/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kemove/anaconda3/envs/dreamgs/lib/python3.9/site-packages/open_clip/transformer.py", line 263, in forward
    x = q_x + self.ls_1(self.attention(q_x=self.ln_1(q_x), k_x=k_x, v_x=v_x, attn_mask=attn_mask))
  File "/home/kemove/anaconda3/envs/dreamgs/lib/python3.9/site-packages/open_clip/transformer.py", line 250, in attention
    return self.attn(
  File "/home/kemove/anaconda3/envs/dreamgs/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kemove/anaconda3/envs/dreamgs/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kemove/anaconda3/envs/dreamgs/lib/python3.9/site-packages/torch/nn/modules/activation.py", line 1275, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "/home/kemove/anaconda3/envs/dreamgs/lib/python3.9/site-packages/torch/nn/functional.py", line 5438, in multi_head_attention_forward
    raise RuntimeError(f"The shape of the 2D attn_mask is {attn_mask.shape}, but should be {correct_2d_size}.")
RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).
`

**Comment by SkevyHoo** [comment]
I met this error two.  :(

**Comment by qixuanwang-233** [comment]
Hello, I also encountered the same problem, may I ask you to solve it？

**Comment by tomatoChenBM** [comment]
same problem helpppp
