### ISSUE TITLE
The problem for Image+Text-to-3D (ImageDream) and Text-to-3D (MVDream)

### ISSUE THREAD

**Issue by qixuanwang-233** [dreamgaussian/dreamgaussian#165]
**When I run these two, I get this error: RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1). Specific errors are as follows:**
F:\Miniconda\envs\dream\lib\site-packages\torch\nn\modules\activation.py:1196: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  return torch._native_multi_head_attention(
IS THERE 1?
Traceback (most recent call last):
  File "F:\project\dreamgaussian\main.py", line 917, in <module>
    gui.train(opt.iters)
  File "F:\project\dreamgaussian\main.py", line 891, in train
    self.prepare_train()
  File "F:\project\dreamgaussian\main.py", line 175, in prepare_train
    self.guidance_sd.get_image_text_embeds(self.input_img_torch, [self.prompt], [self.negative_prompt])
  File "F:\Miniconda\envs\dream\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\project\dreamgaussian\guidance\imagedream_utils.py", line 57, in get_image_text_embeds
    pos_embeds = self.encode_text(prompts).repeat(5,1,1)
  File "F:\project\dreamgaussian\guidance\imagedream_utils.py", line 66, in encode_text
    embeddings = self.model.get_learned_conditioning(prompt).to(self.device)
  File "F:\Miniconda\envs\dream\lib\site-packages\imagedream\ldm\interface.py", line 177, in get_learned_conditioning
    return self.clip_model(prompts)
  File "F:\Miniconda\envs\dream\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\Miniconda\envs\dream\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\Miniconda\envs\dream\lib\site-packages\imagedream\ldm\modules\encoders\modules.py", line 218, in forward
    z = self.encode_with_transformer(tokens.to(self.device))
  File "F:\Miniconda\envs\dream\lib\site-packages\imagedream\ldm\modules\encoders\modules.py", line 282, in encode_with_transformer
    x = self.text_transformer_forward(x, attn_mask=self.model.attn_mask)
  File "F:\Miniconda\envs\dream\lib\site-packages\imagedream\ldm\modules\encoders\modules.py", line 297, in text_transformer_forward
    x = r(x, attn_mask=attn_mask)
  File "F:\Miniconda\envs\dream\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\Miniconda\envs\dream\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\Miniconda\envs\dream\lib\site-packages\open_clip\transformer.py", line 263, in forward
    x = q_x + self.ls_1(self.attention(q_x=self.ln_1(q_x), k_x=k_x, v_x=v_x, attn_mask=attn_mask))
  File "F:\Miniconda\envs\dream\lib\site-packages\open_clip\transformer.py", line 250, in attention
    return self.attn(
  File "F:\Miniconda\envs\dream\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\Miniconda\envs\dream\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\Miniconda\envs\dream\lib\site-packages\torch\nn\modules\activation.py", line 1241, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "F:\Miniconda\envs\dream\lib\site-packages\torch\nn\functional.py", line 5354, in multi_head_attention_forward
    raise RuntimeError(f"The shape of the 2D attn_mask is {attn_mask.shape}, but should be {correct_2d_size}.")
RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).
**Can someone help with this?**

**Comment by tomatoChenBM** [comment]
same problem

**Comment by qinyuxin010328** [comment]
Hi, I encoutered the same problem, and I tried "pip install open-clip-torch==2.24.0". It worked on my server.

**Comment by qixuanwang-233** [comment]
> Hi, I encoutered the same problem, and I tried "pip install open-clip-torch==2.24.0". It worked on my server.

Thank you for your answer, successfully solved this problem! : ）

**Comment by MaggieLxj** [comment]
Thank you for your answer, successfully solved this problem! : ） @qinyuxin010328
