### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by carlosedubarreto** [dreamgaussian/dreamgaussian#28]
Great code.
But I'm having problems testing with custom images. I'm having this issue.

```
(dreamgaussian) D:\AI\dreamgaussian\dreamgaussian-main>python main.py --config configs/image.yaml input=data/gt25m.png save_path=gt25m
[INFO] load image from data/gt25m.png...
[INFO] load prompt from data/gt25m.png...
Traceback (most recent call last):
  File "D:\AI\dreamgaussian\dreamgaussian-main\main.py", line 877, in <module>
    gui = GUI(opt)
  File "D:\AI\dreamgaussian\dreamgaussian-main\main.py", line 67, in __init__
    self.load_input(self.opt.input)
  File "D:\AI\dreamgaussian\dreamgaussian-main\main.py", line 367, in load_input
    self.prompt = f.read().strip()
  File "C:\Users\carlo\miniconda3\envs\dreamgaussian\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 130: character maps to <undefined>
```

Can you give me some hints of what can I do to solve it?
thanks

**Comment by carlosedubarreto** [comment]
I went to debug and found that I must have "_rgba" on the name of the file.

So, renaming my file from` "gt25m.png"` to `"gt25m_rgba.png"` solved the issue.
