### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'logs/tmp_mesh.glb'

### ISSUE THREAD

**Issue by kuyin** [dreamgaussian/dreamgaussian#35]
python gradio_app.py
Running on local URL:  http://127.0.0.1:7860

//When I press Generate 3D button.It shows errors like following.

Traceback (most recent call last):
  File "C:\Users\wyj35\miniconda3\envs\dreamgaussian\lib\site-packages\gradio\queueing.py", line 406, in call_prediction    output = await route_utils.call_process_api(
  File "C:\Users\wyj35\miniconda3\envs\dreamgaussian\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\wyj35\miniconda3\envs\dreamgaussian\lib\site-packages\gradio\blocks.py", line 1563, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\wyj35\miniconda3\envs\dreamgaussian\lib\site-packages\gradio\blocks.py", line 1451, in postprocess_data    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\wyj35\miniconda3\envs\dreamgaussian\lib\site-packages\gradio\components\model3d.py", line 172, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "C:\Users\wyj35\miniconda3\envs\dreamgaussian\lib\site-packages\gradio\components\base.py", line 233, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "C:\Users\wyj35\miniconda3\envs\dreamgaussian\lib\site-packages\gradio\components\base.py", line 197, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/tmp_mesh.glb'

How to solve this?

**Comment by kuyin** [comment]
> @kuyin Hi, could you give more details like the command you are using?

Commands works fine but gradio demo has bug here on win11 cuda118.

**Comment by ashawkey** [comment]
This should be fixed with the latest code, you could try again!

**Comment by yuchenlichuck** [comment]
I have the same errors
[INFO] load image from tmp_data/tmp_rgba.png...
Number of points at initialisation :  5000
[INFO] loading zero123...
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 19.05it/s]
[INFO] loaded zero123!
100%|██████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:25<00:00, 19.61it/s]
[INFO] save model to logs/tmp_model.ply.
/home/dubaiprince/miniconda3/envs/gsgen/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/dubaiprince/miniconda3/envs/gsgen/lib/python3.9/site-packages/varname/utils.py:447: UsingExecWarning: Cannot evaluate node Attribute(value=Name(id='kiui', ctx=Load()), attr='lo', ctx=Load()) using 'pure_eval'. Using 'eval' to get the function that calls 'argname'. Try calling it using a variable reference to the function, or passing the function to 'argname' explicitly.
  warnings.warn(
Tensor occ torch.Size([128, 128, 128]) torch.float32 cuda:0∈ [0.0, 49.60915756225586] μ = 0.3278807997703552 σ = 
1.9606040716171265
[INFO] mesh cleaning: (22562, 3) --> (11269, 3), (45116, 3) --> (22534, 3)
[INFO] marching cubes result: torch.Size([11269, 3]) (-0.6817220449447632-0.6762968301773071), torch.Size([22534, 3])
[INFO] unwrap uv...
Traceback (most recent call last):
  File "/home/dubaiprince/Projects/dreamgaussian/main.py", line 882, in <module>
    gui.train(opt.iters)
  File "/home/dubaiprince/Projects/dreamgaussian/main.py", line 863, in train
    self.save_model(mode='geo+tex')
  File "/home/dubaiprince/miniconda3/envs/gsgen/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/dubaiprince/Projects/dreamgaussian/main.py", line 503, in save_model
    mesh.write(path)
  File "/home/dubaiprince/Projects/dreamgaussian/mesh.py", line 429, in write
    self.write_glb(path)
  File "/home/dubaiprince/Projects/dreamgaussian/mesh.py", line 453, in write_glb
    import pygltflib
ModuleNotFoundError: No module named 'pygltflib'
Traceback (most recent call last):
  File "/home/dubaiprince/miniconda3/envs/gsgen/lib/python3.9/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/dubaiprince/miniconda3/envs/gsgen/lib/python3.9/site-packages/gradio/route_utils.py", line 217, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/dubaiprince/miniconda3/envs/gsgen/lib/python3.9/site-packages/gradio/blocks.py", line 1562, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/dubaiprince/miniconda3/envs/gsgen/lib/python3.9/site-packages/gradio/blocks.py", line 1450, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/dubaiprince/miniconda3/envs/gsgen/lib/python3.9/site-packages/gradio/components/model3d.py", line 172, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "/home/dubaiprince/miniconda3/envs/gsgen/lib/python3.9/site-packages/gradio/components/base.py", line 217, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/home/dubaiprince/miniconda3/envs/gsgen/lib/python3.9/site-packages/gradio/components/base.py", line 181, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/tmp_mesh.glb'

**Comment by neciszhang** [comment]
Have same question:
[INFO] loaded zero123!
100%|██████████| 500/500 [01:16<00:00,  6.56it/s]
/usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[INFO] save model to logs/necis_model.ply.
Tensor occ torch.Size([128, 128, 128]) torch.float32 cuda:0 ∈ [0.0, 15.82831859588623] μ = 0.15369579195976257 σ = 
0.7341219782829285
[INFO] mesh cleaning: (25804, 3) --> (12624, 3), (51596, 3) --> (25244, 3)
[INFO] marching cubes result: torch.Size([12624, 3]) (-0.6795961856842041-0.4470672607421875), torch.Size([25244, 3])
[INFO] unwrap uv...
[INFO] save model to logs/necis_mesh.obj.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/dreamgaussian/main2.py](https://localhost:8080/#) in <module>
    684             opt.mesh = default_path
    685         else:
--> 686             raise ValueError(f"Cannot find mesh from {default_path}, must specify --mesh explicitly!")
    687 
    688     gui = GUI(opt)

ValueError: Cannot find mesh from logs/necis_mesh.glb, must specify --mesh explicitly!

**Comment by nukadelic** [comment]
same here

**Comment by v4r4rth** [comment]
Also facing the same issue:

python process.py tmp_data/tmp.png
/usr/local/lib/python3.8/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
EP Error /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1193 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libnvinfer.so.8: cannot open shared object file: No such file or directory
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'AzureExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
[INFO] loading image tmp_data/tmp.png...
[INFO] background removal...
[INFO] recenter...
/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:611: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
[INFO] load image from tmp_data/tmp_rgba.png...
Number of points at initialisation :  5000
[INFO] loading zero123...
/usr/local/lib/python3.8/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Keyword arguments {'trust_remote_code': True} are not expected by Zero123Pipeline and will be ignored.
Loading pipeline components...:   0%|                                                                                                                                  | 0/6 [00:00<?, ?it/s]The config attributes {'attention_type': 'default', 'dropout': 0.0, 'reverse_transformer_layers_per_block': None} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00,  9.11it/s]
[INFO] loaded zero123!
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:35<00:00, 13.96it/s]
[INFO] save model to logs/tmp_model.ply.
/usr/local/lib/python3.8/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Tensor occ torch.Size([128, 128, 128]) torch.float32 cuda:0 ∈ [0.0, 65.020751953125] μ = 0.5169093608856201 σ = 3.035029888153076
Traceback (most recent call last):
  File "main.py", line 905, in <module>
    gui.train(opt.iters)
  File "main.py", line 886, in train
    self.save_model(mode='geo+tex')
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "main.py", line 402, in save_model
    mesh = self.renderer.gaussians.extract_mesh(path, self.opt.density_thresh)
  File "/root/dreamgaussian/gs_renderer.py", line 309, in extract_mesh
    vertices, triangles = clean_mesh(vertices, triangles, remesh=True, remesh_size=0.015)
  File "/root/dreamgaussian/mesh_utils.py", line 113, in clean_mesh
    threshold=pml.PercentageValue(v_pct)
AttributeError: module 'pymeshlab' has no attribute 'PercentageValue'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1559, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1447, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.8/dist-packages/gradio/components/model3d.py", line 172, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "/usr/local/lib/python3.8/dist-packages/gradio/components/base.py", line 233, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/usr/local/lib/python3.8/dist-packages/gradio/components/base.py", line 197, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/tmp_mesh.glb'

**Comment by xPr0xi** [comment]
Same Issue here:
```

CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
[INFO] loading image tmp_data\tmp.png...
[INFO] background removal...
[INFO] recenter...
C:\Users\whnan\anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Traceback (most recent call last):
  File "C:\Users\whnan\dreamg\main.py", line 14, in <module>
    from gs_renderer import Renderer, MiniCam
  File "C:\Users\whnan\dreamg\gs_renderer.py", line 10, in <module>
    from diff_gaussian_rasterization import (
  File "C:\Users\whnan\dreamg\diff_gaussian_rasterization\__init__.py", line 15, in <module>
    from . import _C
ImportError: cannot import name '_C' from partially initialized module 'diff_gaussian_rasterization' (most likely due to a circular import) (C:\Users\whnan\dreamg\diff_gaussian_rasterization\__init__.py)
Traceback (most recent call last):
  File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\blocks.py", line 1542, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\blocks.py", line 1428, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "C:\Users\whnan\anaconda3\lib\site-packages\gradio_client\utils.py", line 917, in traverse
    return func(json_obj)
  File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\blocks.py", line 257, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\whnan\\dreamg\\logs\\tmp_mesh.glb'

```

**Comment by 1986727548** [comment]
> python gradio_app.py Running on local URL: http://127.0.0.1:7860
> 
> //When I press Generate 3D button.It shows errors like following.
> 
> Traceback (most recent call last): File "C:\Users\wyj35\miniconda3\envs\dreamgaussian\lib\site-packages\gradio\queueing.py", line 406, in call_prediction output = await route_utils.call_process_api( File "C:\Users\wyj35\miniconda3\envs\dreamgaussian\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api output = await app.get_blocks().process_api( File "C:\Users\wyj35\miniconda3\envs\dreamgaussian\lib\site-packages\gradio\blocks.py", line 1563, in process_api data = self.postprocess_data(fn_index, result["prediction"], state) File "C:\Users\wyj35\miniconda3\envs\dreamgaussian\lib\site-packages\gradio\blocks.py", line 1451, in postprocess_data prediction_value = block.postprocess(prediction_value) File "C:\Users\wyj35\miniconda3\envs\dreamgaussian\lib\site-packages\gradio\components\model3d.py", line 172, in postprocess "name": self.make_temp_copy_if_needed(y), File "C:\Users\wyj35\miniconda3\envs\dreamgaussian\lib\site-packages\gradio\components\base.py", line 233, in make_temp_copy_if_needed temp_dir = self.hash_file(file_path) File "C:\Users\wyj35\miniconda3\envs\dreamgaussian\lib\site-packages\gradio\components\base.py", line 197, in hash_file with open(file_path, "rb") as f: FileNotFoundError: [Errno 2] No such file or directory: 'logs/tmp_mesh.glb'
> 
> How to solve this?

I resolved it by connecting to a VPN and setting up a proxy.
For set vpn, there exist some problem!!!
in my computer(ubuntu)
>> echo $all_proxy
it will print  socks://127.0.0.1:7890/
>> export all_proxy = http://127.0.0.1:7890/
then, python gradio_app.py. it is ok. use vpn is essential.

**Comment by 1986727548** [comment]
> Same Issue here, rtx 3090, win11:
> 
> ```
> 
> CryptographyDeprecationWarning: Blowfish has been deprecated
>   "class": algorithms.Blowfish,
> [INFO] loading image tmp_data\tmp.png...
> [INFO] background removal...
> [INFO] recenter...
> C:\Users\whnan\anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
>   "class": algorithms.Blowfish,
> Traceback (most recent call last):
>   File "C:\Users\whnan\dreamg\main.py", line 14, in <module>
>     from gs_renderer import Renderer, MiniCam
>   File "C:\Users\whnan\dreamg\gs_renderer.py", line 10, in <module>
>     from diff_gaussian_rasterization import (
>   File "C:\Users\whnan\dreamg\diff_gaussian_rasterization\__init__.py", line 15, in <module>
>     from . import _C
> ImportError: cannot import name '_C' from partially initialized module 'diff_gaussian_rasterization' (most likely due to a circular import) (C:\Users\whnan\dreamg\diff_gaussian_rasterization\__init__.py)
> Traceback (most recent call last):
>   File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\queueing.py", line 489, in call_prediction
>     output = await route_utils.call_process_api(
>   File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
>     output = await app.get_blocks().process_api(
>   File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\blocks.py", line 1542, in process_api
>     data = self.postprocess_data(fn_index, result["prediction"], state)
>   File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\blocks.py", line 1428, in postprocess_data
>     outputs_cached = processing_utils.move_files_to_cache(
>   File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache
>     return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
>   File "C:\Users\whnan\anaconda3\lib\site-packages\gradio_client\utils.py", line 917, in traverse
>     return func(json_obj)
>   File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache
>     temp_file_path = move_resource_to_block_cache(payload.path, block)
>   File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
>     return block.move_resource_to_block_cache(url_or_file_path)
>   File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\blocks.py", line 257, in move_resource_to_block_cache
>     temp_file_path = processing_utils.save_file_to_cache(
>   File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
>     temp_dir = hash_file(file_path)
>   File "C:\Users\whnan\anaconda3\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
>     with open(file_path, "rb") as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\whnan\\dreamg\\logs\\tmp_mesh.glb'
> ```

I resolved it by connecting to a VPN and setting up a proxy.
For set vpn, there exist some problem!!!
in my computer(ubuntu)
>> echo $all_proxy
it will print  socks://127.0.0.1:7890/
>> export all_proxy = http://127.0.0.1:7890/
then, python gradio_app.py. it is ok. use vpn is essential.
