### ISSUE TITLE
CUDA

### ISSUE THREAD

**Issue by Fanie-Visagie** [dreamgaussian/dreamgaussian#40]
Not sure why I am getting this error...I do have a RTX 3080 that is Cuda Compatible...

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\perso\gaussian-splatting\dreamgaussian-main\main.py:882 in <module>                     │
│                                                                                                  │
│   879 │   if opt.gui:                                                                            │
│   880 │   │   gui.render()                                                                       │
│   881 │   else:                                                                                  │
│ ❱ 882 │   │   gui.train(opt.iters)                                                               │
│   883                                                                                            │
│                                                                                                  │
│ C:\Users\perso\gaussian-splatting\dreamgaussian-main\main.py:863 in train                        │
│                                                                                                  │
│   860 │   │   │   self.renderer.gaussians.prune(min_opacity=0.01, extent=1, max_screen_size=1)   │
│   861 │   │   # save                                                                             │
│   862 │   │   self.save_model(mode='model')                                                      │
│ ❱ 863 │   │   self.save_model(mode='geo+tex')                                                    │
│   864                                                                                            │
│   865                                                                                            │
│   866 if __name__ == "__main__":                                                                 │
│                                                                                                  │
│ C:\Users\perso\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\autograd\grad_mode.py:2 │
│ 7 in decorate_context                                                                            │
│                                                                                                  │
│    24 │   │   @functools.wraps(func)                                                             │
│    25 │   │   def decorate_context(*args, **kwargs):                                             │
│    26 │   │   │   with self.clone():                                                             │
│ ❱  27 │   │   │   │   return func(*args, **kwargs)                                               │
│    28 │   │   return cast(F, decorate_context)                                                   │
│                                                                                                  │
│ C:\Users\perso\gaussian-splatting\dreamgaussian-main\main.py:416 in save_model                   │
│                                                                                                  │
│   413 │   │   │   │   │   self.cam.fovy,                                                         │
│   414 │   │   │   │   │   self.cam.fovx,                                                         │
│   415 │   │   │   │   │   self.cam.near,                                                         │
│ ❱ 416 │   │   │   │   │   self.cam.far,                                                          │
│   417 │   │   │   │   )                                                                          │
│   418 │   │   │   │                                                                              │
│   419 │   │   │   │   cur_out = self.renderer.render(cur_cam)                                    │
│                                                                                                  │
│ C:\Users\perso\gaussian-splatting\dreamgaussian-main\gs_renderer.py:660 in __init__              │
│                                                                                                  │
│   657 │   │   w2c[1:3, :3] *= -1                                                                 │
│   658 │   │   w2c[:3, 3] *= -1                                                                   │
│   659 │   │                                                                                      │
│ ❱ 660 │   │   self.world_view_transform = torch.tensor(w2c).transpose(0, 1).cuda()               │
│   661 │   │   self.projection_matrix = (                                                         │
│   662 │   │   │   getProjectionMatrix(                                                           │
│   663 │   │   │   │   znear=self.znear, zfar=self.zfar, fovX=self.FoVx, fovY=self.FoVy

RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
(gaussian_splatting) PS C:\Users\perso\gaussian-splatting\dreamgaussian-main> python
Python 3.7.13 (default, Oct 19 2022, 10:19:43) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
>>> CUDA_LAUNCH_BLOCKING=1
>>>

**Comment by ashawkey** [comment]
@Fanie-Visagie Could you share the command line that leads to this? Also, you can try adding `CUDA_LAUNCH_BLOCKING=1` to see more details.

**Comment by Fanie-Visagie** [comment]
Optimizing
Output folder: ./output/b90a30bc-c [19/10 09:46:36]
Tensorboard not available: not logging progress [19/10 09:46:36]
Reading camera 1/211C:\Users\perso\.conda\envs\gaussian_splatting\lib\site-packages\PIL\TiffImagePlugin.py:845: UserWarning: Corrupt EXIF data.  Expecting to read 2 bytes but only got 0.
  warnings.warn(str(msg))
Reading camera 211/211 [19/10 09:46:36]
Converting point3d.bin to .ply, will happen only the first time you open the scene. [19/10 09:46:36]
Loading Training Cameras [19/10 09:46:37]
[ INFO ] Encountered quite large input images (>1.6K pixels width), rescaling to 1.6K.
 If this is not desired, please explicitly specify '--resolution/-r' as 1 [19/10 09:46:37]
Loading Test Cameras [19/10 09:49:05]
Number of points at initialisation :  164713 [19/10 09:49:05]
Training progress:  23%|██████████████████▏                                                           | 7000/30000 [07:14<27:02, 14.18it/s, Loss=0.0795816]
[ITER 7000] Evaluating train: L1 0.039562239125370983 PSNR 23.394759750366212 [19/10 09:56:21]

[ITER 7000] Saving Gaussians [19/10 09:56:21]
Training progress:  37%|████████████████████████████▍                                                | 11060/30000 [12:59<30:20, 10.40it/s, Loss=0.0939627]Traceback (most recent call last):
  File "train.py", line 216, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 83, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background)
  File "F:\gaussian-splatting\gaussian_renderer\__init__.py", line 99, in render
    "visibility_filter" : radii > 0,
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Training progress:  37%|████████████████████████████▍

Happened again, this time during training...

**Comment by ashawkey** [comment]
I don't think this is the output from this repo...

**Comment by WesleyXu224** [comment]
hello,How did you solve this problem? I also encountered the same problem...
