### ISSUE TITLE
Run fails

### ISSUE THREAD

**Issue by yuchenlichuck** [dreamgaussian/dreamgaussian#5]
Some bugs in the code

```
~/Projects/dreamgaussian$ CUDA_VISIBLE_DEVICES=0 python main.py --config configs/text.yaml prompt="a photo of an icecream" save_path=icecream
Warning:
Unable to load the following plugins:

	libio_e57.so: libio_e57.so does not seem to be a Qt Plugin.
pymeshlab/lib/plugins/libio_e57.so: (/lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0)

Number of points at initialisation :  1000
[INFO] loading SD...
Downloading (…)ch_model.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████| 335M/335M [00:29<00:00, 11.4MB/s]
Downloading model.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 1.36G/1.36G [01:27<00:00, 15.6MB/s]
Downloading (…)ch_model.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████| 3.46G/3.46G [02:35<00:00, 22.3MB/s]
Fetching 13 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [02:35<00:00, 11.99s/it]
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00,  9.52it/s]
[INFO] loaded SD!_model.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████| 3.46G/3.46G [02:35<00:00, 30.0MB/s]
  0%|                                                                                                                                       | 0/500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/dubaiprince/Projects/dreamgaussian/main.py", line 882, in <module>
    gui.train(opt.iters)
  File "/home/dubaiprince/Projects/dreamgaussian/main.py", line 858, in train
    self.train_step()
  File "/home/dubaiprince/Projects/dreamgaussian/main.py", line 218, in train_step
    out = self.renderer.render(cur_cam, invert_bg_color=invert_bg_color)
  File "/home/dubaiprince/Projects/dreamgaussian/gs_renderer.py", line 798, in render
    rendered_image, radii, rendered_depth, rendered_alpha = rasterizer(
ValueError: not enough values to unpack (expected 4, got 2)

```

**Comment by ashawkey** [comment]
@yuchenlichuck Hi, please install the correct `diff-gaussian-rasterization`, we use a modified version:
``` bash
# a modified gaussain splatting (+ depth, alpha rendering)
git clone --recursive https://github.com/ashawkey/diff-gaussian-rasterization
pip install ./diff-gaussian-rasterization

```

**Comment by yuchenlichuck** [comment]
thank you
