### ISSUE TITLE
Mesh generation from 3DGS output format

### ISSUE THREAD

**Issue by hodakagoto** [dreamgaussian/dreamgaussian#53]
Can I generate a mesh from [graphdeco-inria/gaussian-splatting](https://github.com/graphdeco-inria/gaussian-splatting) output format?

**Comment by ashawkey** [comment]
@hodakagoto Hi, yes! You can use the `load` config to directly load the `ply` files.

**Comment by hodakagoto** [comment]
@ashawkey I got an error when I ran this command:
`python main.py --config configs/image.yaml load=/path/to/3dgs-output/input.ply`
Am I doing something wrong?

**Comment by camtrik** [comment]
I also tried this command but got an error:
```
python main.py --config configs/image.yaml load=miku.ply gui=True

Number of points at loading :  531242
Traceback (most recent call last):
  File "D:\work\dreamgaussian\main.py", line 915, in <module>
    gui = GUI(opt)
  File "D:\work\dreamgaussian\main.py", line 78, in __init__
    self.renderer.initialize(self.opt.load)
  File "D:\work\dreamgaussian\gs_renderer.py", line 713, in initialize
    self.gaussians.load_ply(input)
  File "D:\work\dreamgaussian\gs_renderer.py", line 438, in load_ply
    assert len(extra_f_names)==3*(self.max_sh_degree + 1) ** 2 - 3
AssertionError
```
What should I do?

**Comment by maybeLx** [comment]
maybe you should rename the directory of '3dgs-output' to '3dgs_output' and change the code to "python main.py --config configs/image.yaml load=/path/to/3dgs_output/input.ply"

**Comment by hodakagoto** [comment]
@maybeLx The path is an example and does not actually contain `-`. I get the same error as @camtrik did.

**Comment by WWmore** [comment]
> I also tried this command but got an error:
> 
> ```
> python main.py --config configs/image.yaml load=miku.ply gui=True
> 
> Number of points at loading :  531242
> Traceback (most recent call last):
>   File "D:\work\dreamgaussian\main.py", line 915, in <module>
>     gui = GUI(opt)
>   File "D:\work\dreamgaussian\main.py", line 78, in __init__
>     self.renderer.initialize(self.opt.load)
>   File "D:\work\dreamgaussian\gs_renderer.py", line 713, in initialize
>     self.gaussians.load_ply(input)
>   File "D:\work\dreamgaussian\gs_renderer.py", line 438, in load_ply
>     assert len(extra_f_names)==3*(self.max_sh_degree + 1) ** 2 - 3
> AssertionError
> ```
> 
> What should I do?

the `sh_degree` should be 3. You could set it in image.yaml.

**Comment by WWmore** [comment]
@hodakagoto I think we can not train it (since the loss==0 here), but directly extract_mesh to get a mesh. I tried one example in the GUI window as seen in my note here https://github.com/WWmore/dreamgaussian. Unfortunately, the mesh quality is very bad. And I am also trying to figure out how to get a good mesh with nice texture from given Gaussian Splatting .ply. Maybe the authors or others can solve such problem easier and sooner. Looking forwards to the post.

**Comment by Lewis-lv0** [comment]
Exactly the same issue here. Seems that the code can only works for the case when sh_degree=0. Looking forward to updates about it.

**Comment by yangqing-yq** [comment]
/dc2/dreamgaussian$ python main.py --config configs/image.yaml load=/dc2/SuGaR/output/0001_matting_blackbg/point_cloud/iteration_7000/point_cloud.ply
Number of points at loading :  81269
Traceback (most recent call last):
  File "/dc2/dreamgaussian/main.py", line 921, in <module>
    gui = GUI(opt)
  File "/dc2/dreamgaussian/main.py", line 86, in __init__
    self.renderer.initialize(self.opt.load)
  File "/dc2/dreamgaussian/gs_renderer.py", line 715, in initialize
    self.gaussians.load_ply(input)
  File "/dc2/dreamgaussian/gs_renderer.py", line 438, in load_ply
    assert len(extra_f_names)==3*(self.max_sh_degree + 1) ** 2 - 3
AssertionError


same issue here!!!

**Comment by hxj2580** [comment]
> @hodakagoto I think we can not train it (since the loss==0 here), but directly extract_mesh to get a mesh. I tried one example in the GUI window as seen in my note here https://github.com/WWmore/dreamgaussian. Unfortunately, the mesh quality is very bad. And I am also trying to figure out how to get a good mesh with nice texture from given Gaussian Splatting .ply. Maybe the authors or others can solve such problem easier and sooner. Looking forwards to the post.

老哥，你明白model.ply对于导出obj有什么作用了吗，在哪调用model.ply了

**Comment by hxj2580** [comment]
> AttributeError: 'int' object has no attribute 'backward' 
How to solve the problem？

**Comment by silence-tang** [comment]
> [@hodakagoto](https://github.com/hodakagoto) I think we can not train it (since the loss==0 here), but directly extract_mesh to get a mesh. I tried one example in the GUI window as seen in my note here https://github.com/WWmore/dreamgaussian. Unfortunately, the mesh quality is very bad. And I am also trying to figure out how to get a good mesh with nice texture from given Gaussian Splatting .ply. Maybe the authors or others can solve such problem easier and sooner. Looking forwards to the post.

Hi, my friend, today is 2025.01.27, did you find any method to extract decent textured mesh from 3dgs .ply file? Thanks a lot!

**Comment by hbsaucy** [comment]
++

**Comment by hbsaucy** [comment]
u use py .greytrismagistus
