### ISSUE TITLE
Error [INFO] loading zero123...

### ISSUE THREAD

**Issue by andzejsp** [dreamgaussian/dreamgaussian#59]
Can someone help me?

```
Microsoft Windows [Version 10.0.22621.2428]
(c) Microsoft Corporation. All rights reserved.

D:\Git\dreamgaussian>python gradio_app.py
Running on local URL:  http://127.0.0.1:7860

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
python process.py tmp_data\tmp.png
[INFO] loading image tmp_data\tmp.png...
[INFO] background removal...
[INFO] recenter...
[INFO] load image from tmp_data\tmp_rgba.png...
Number of points at initialisation :  5000
[INFO] loading zero123...
The config attributes {'rescale_betas_zero_snr': False, 'timestep_spacing': 'leading'} were passed to DDIMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
The config attributes {'addition_time_embed_dim': None, 'encoder_hid_dim_type': None, 'num_attention_heads': None, 'transformer_layers_per_block': 1} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Traceback (most recent call last):
  File "D:\Git\dreamgaussian\main.py", line 901, in <module>
    gui.train(opt.iters)
  File "D:\Git\dreamgaussian\main.py", line 875, in train
    self.prepare_train()
  File "D:\Git\dreamgaussian\main.py", line 145, in prepare_train
    self.guidance_zero123 = Zero123(self.device)
  File "D:\Git\dreamgaussian\guidance\zero123_utils.py", line 29, in __init__
    self.pipe = Zero123Pipeline.from_pretrained(
  File "C:\Users\win\miniconda3\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1025, in from_pretrained
    importable_classes = ALL_IMPORTABLE_CLASSES if is_pipeline_module else LOADABLE_CLASSES[library_name]
KeyError: 'zero123'
Traceback (most recent call last):
  File "C:\Users\win\miniconda3\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\win\miniconda3\lib\site-packages\gradio\blocks.py", line 1395, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\win\miniconda3\lib\site-packages\gradio\blocks.py", line 1329, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\win\miniconda3\lib\site-packages\gradio\components\model3d.py", line 148, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "C:\Users\win\miniconda3\lib\site-packages\gradio\components\base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "C:\Users\win\miniconda3\lib\site-packages\gradio\components\base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs\\tmp_mesh.glb'
```

Not sure how to fix this. Before this i was getting no module triton, then i used the link https://github.com/dreamgaussian/dreamgaussian/issues/39#issuecomment-1764198817 and now im getting this.

```
C:\Users\win>python -V
Python 3.10.10

C:\Users\win>
```

**Comment by andzejsp** [comment]
Updated conda and python, and rerun pip installs and now im getting this:
```
D:\Git\dreamgaussian>python gradio_app.py
Running on local URL:  http://127.0.0.1:7860

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
python process.py tmp_data\tmp.png
[INFO] loading image tmp_data\tmp.png...
[INFO] background removal...
[INFO] recenter...
[INFO] load image from tmp_data\tmp_rgba.png...
Number of points at initialisation :  5000
[INFO] loading zero123...
Traceback (most recent call last):
  File "D:\Git\dreamgaussian\main.py", line 901, in <module>
    gui.train(opt.iters)
  File "D:\Git\dreamgaussian\main.py", line 875, in train
    self.prepare_train()
  File "D:\Git\dreamgaussian\main.py", line 145, in prepare_train
    self.guidance_zero123 = Zero123(self.device)
  File "D:\Git\dreamgaussian\guidance\zero123_utils.py", line 29, in __init__
    self.pipe = Zero123Pipeline.from_pretrained(
  File "C:\Users\win\miniconda3\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1039, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "C:\Users\win\miniconda3\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 445, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "C:\Users\win\miniconda3\lib\site-packages\diffusers\models\modeling_utils.py", line 583, in from_pretrained
    raise ValueError(
ValueError: Cannot load <class 'diffusers.models.autoencoder_kl.AutoencoderKL'> from C:\Users\win\.cache\huggingface\hub\models--bennyguo--zero123-xl-diffusers\snapshots\ae385edfaf74c677408f96bd04b513483bd326ac\vae because the following keys are missing:
 encoder.mid_block.attentions.0.proj_attn.bias, encoder.mid_block.attentions.0.value.bias, decoder.mid_block.attentions.0.query.bias, encoder.mid_block.attentions.0.proj_attn.weight, encoder.mid_block.attentions.0.key.weight, decoder.mid_block.attentions.0.value.weight, encoder.mid_block.attentions.0.value.weight, decoder.mid_block.attentions.0.proj_attn.weight, encoder.mid_block.attentions.0.query.weight, decoder.mid_block.attentions.0.key.weight, decoder.mid_block.attentions.0.value.bias, encoder.mid_block.attentions.0.key.bias, encoder.mid_block.attentions.0.query.bias, decoder.mid_block.attentions.0.key.bias, decoder.mid_block.attentions.0.query.weight, decoder.mid_block.attentions.0.proj_attn.bias.
 Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct.
Traceback (most recent call last):
  File "C:\Users\win\miniconda3\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\win\miniconda3\lib\site-packages\gradio\blocks.py", line 1395, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\win\miniconda3\lib\site-packages\gradio\blocks.py", line 1329, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\win\miniconda3\lib\site-packages\gradio\components\model3d.py", line 148, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "C:\Users\win\miniconda3\lib\site-packages\gradio\components\base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "C:\Users\win\miniconda3\lib\site-packages\gradio\components\base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs\\tmp_mesh.glb'
```

```
D:\Git\dreamgaussian>python -V
Python 3.10.13
```
