### ISSUE TITLE
Failed building wheel for diff-gaussian-rasterization / TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by Ratinod** [dreamgaussian/dreamgaussian#6]
I get this after:  `pip install ./diff-gaussian-rasterization`
Any ideas on how to fix?
```
(venv) M:\_SD\dreamgaussian>pip install ./diff-gaussian-rasterization
Processing m:\_sd\dreamgaussian\diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff-gaussian-rasterization
  Building wheel for diff-gaussian-rasterization (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\diff_gaussian_rasterization
      copying diff_gaussian_rasterization\__init__.py -> build\lib.win-amd64-cpython-310\diff_gaussian_rasterization
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "M:\_SD\dreamgaussian\diff-gaussian-rasterization\setup.py", line 17, in <module>
          setup(
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\wheel\bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\torch\utils\cpp_extension.py", line 383, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
          return Version(version)
        File "M:\_SD\dreamgaussian\venv\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 196, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects
```

**Comment by ashawkey** [comment]
@Ratinod Hi, could you verify your CUDA installation?

**Comment by DiamondGlassDrill** [comment]
**I do have the same issue:**

I have several CUDA versions installed and tried all of them with CUDE_HOME path change on Windows 11, but fails in every with this error:

CUDA_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2

**Verify CUDA version :** nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jul_11_03:10:21_Pacific_Daylight_Time_2023
Cuda compilation tools, release 12.2, V12.2.128
Build cuda_12.2.r12.2/compiler.33053471_0

**Comment by MALIKKHU** [comment]
The error message you're encountering suggests that there's a problem with building the wheel for the diff-gaussian-rasterization package, particularly during the python setup.py bdist_wheel step.
Check setup.py File:
Examine the setup.py file in the diff-gaussian-rasterization package. Ensure that the setup() function is defined correctly and all required dependencies and configurations are included.

**Comment by Ratinod** [comment]
> could you verify your CUDA installation?

nvcc --version
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
```

**Comment by DiamondGlassDrill** [comment]
Solved it with 

1. pip uninstall torch

and reinstall with pytorch

2. conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia

**Comment by Ratinod** [comment]
> Solved it with
> 
>     1. pip uninstall torch
> 
> 
> and reinstall with pytorch
> 
>     2. conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia

Yes. Now everything installs without errors...
But nothing works...
First command from the "Usage" section:
`python process.py data/anya_rgba.png`
```
(drgaus) M:\_SD\dreamgaussian>python process.py data/anya_rgba.png
Traceback (most recent call last):
  File "D:\anaconda3\envs\drgaus\lib\site-packages\requests\compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\_SD\dreamgaussian\process.py", line 12, in <module>
    from torchvision import transforms
  File "D:\anaconda3\envs\drgaus\lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "D:\anaconda3\envs\drgaus\lib\site-packages\torchvision\datasets\__init__.py", line 1, in <module>
    from ._optical_flow import FlyingChairs, FlyingThings3D, HD1K, KittiFlow, Sintel
  File "D:\anaconda3\envs\drgaus\lib\site-packages\torchvision\datasets\_optical_flow.py", line 13, in <module>
    from .utils import _read_pfm, verify_str_arg
  File "D:\anaconda3\envs\drgaus\lib\site-packages\torchvision\datasets\utils.py", line 22, in <module>
    import requests
  File "D:\anaconda3\envs\drgaus\lib\site-packages\requests\__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "D:\anaconda3\envs\drgaus\lib\site-packages\requests\exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "D:\anaconda3\envs\drgaus\lib\site-packages\requests\compat.py", line 13, in <module>
    import charset_normalizer as chardet
  File "D:\anaconda3\envs\drgaus\lib\site-packages\charset_normalizer\__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "D:\anaconda3\envs\drgaus\lib\site-packages\charset_normalizer\api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
  File "charset_normalizer\md.py", line 5, in <module>
ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (D:\anaconda3\envs\drgaus\lib\site-packages\charset_normalizer\constant.py)
```
ok...
`pip install chardet`
`python process.py data/anya_rgba.png`
```
(drgaus) M:\_SD\dreamgaussian>python process.py data/anya_rgba.png
Traceback (most recent call last):
  File "M:\_SD\dreamgaussian\process.py", line 14, in <module>
    import rembg
  File "D:\anaconda3\envs\drgaus\lib\site-packages\rembg\__init__.py", line 5, in <module>
    from .bg import remove
  File "D:\anaconda3\envs\drgaus\lib\site-packages\rembg\bg.py", line 16, in <module>
    from pymatting.alpha.estimate_alpha_cf import estimate_alpha_cf
  File "D:\anaconda3\envs\drgaus\lib\site-packages\pymatting\__init__.py", line 2, in <module>
    from pymatting.util import *
  File "D:\anaconda3\envs\drgaus\lib\site-packages\pymatting\util\__init__.py", line 2, in <module>
    from pymatting.util.kdtree import KDTree, knn
  File "D:\anaconda3\envs\drgaus\lib\site-packages\pymatting\util\kdtree.py", line 2, in <module>
    from numba import njit, prange
  File "D:\anaconda3\envs\drgaus\lib\site-packages\numba\__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "D:\anaconda3\envs\drgaus\lib\site-packages\numba\__init__.py", line 42, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.25 or less")
ImportError: Numba needs NumPy 1.25 or less
```
ok......
`pip install numpy==1.25`

And only now everything works...
