### ISSUE TITLE
Missing key MVDREAM

### ISSUE THREAD

**Issue by DiamondGlassDrill** [dreamgaussian/dreamgaussian#60]
I get since the MVDream addon the following issue without using MVDream just wanted to execute main.py, as I did last week before the addon:
python main.py --config configs/image_own.yaml input=data/With_background_rgba.png save_path=dog elevation=0

Traceback (most recent call last):
  File "...\Generate3D\dreamgaussian\main.py", line 901, in <module>
    gui.train(opt.iters)
  File "...\Generate3D\dreamgaussian\main.py", line 877, in train
    self.train_step()
  File "...\Generate3D\dreamgaussian\main.py", line 225, in train_step
    if self.opt.mvdream:
  File "...\mambaforge\envs\dreamgaussian\lib\site-packages\omegaconf\dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "...\mambaforge\envs\dreamgaussian\lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "...\mambaforge\envs\dreamgaussian\lib\site-packages\omegaconf\_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "...\mambaforge\envs\dreamgaussian\lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "...\mambaforge\envs\dreamgaussian\lib\site-packages\omegaconf\dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "...\mambaforge\envs\dreamgaussian\lib\site-packages\omegaconf\dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "...\mambaforge\envs\dreamgaussian\lib\site-packages\omegaconf\basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "...\mambaforge\envs\dreamgaussian\lib\site-packages\omegaconf\dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key mvdream
    full_key: mvdream
    object_type=dict

**Comment by DiamondGlassDrill** [comment]
Solved :) 
My own yaml had no MVDREAM option :) e.g. mvdream: False
