### ISSUE TITLE
Network failure occurs when loading zero123

### ISSUE THREAD

**Issue by TsingyuanChou** [dreamgaussian/dreamgaussian#74]
`[INFO] loading zero123...
Traceback (most recent call last):
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f33c0792cd0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bennyguo/zero123-xl-diffusers (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f33c0792cd0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 901, in <module>
    gui.train(opt.iters)
  File "main.py", line 875, in train
    self.prepare_train()
  File "main.py", line 145, in prepare_train
    self.guidance_zero123 = Zero123(self.device)
  File "/home/lancer/dreamgaussian/guidance/zero123_utils.py", line 29, in __init__
    self.pipe = Zero123Pipeline.from_pretrained(            
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 939, in from_pretrained
    cached_folder = cls.download(
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 1441, in download
    info = model_info(
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 1697, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bennyguo/zero123-xl-diffusers (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f33c0792cd0>: Failed to establish a new connection: [Errno 110] Connection timed out'))"), '(Request ID: ac1df403-7df9-489f-b9c9-7f9d7ad8cd24)')
`

Can I git zero123 to the specified folder myself to solve this problem?

**Comment by zhanxiaopan** [comment]
@TsingyuanChou 
Hi Chou,  I have the same issue.  Have you fixed it？

**Comment by yangqinhui0423** [comment]
> `[INFO] loading zero123... Traceback (most recent call last): File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn conn = connection.create_connection( File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection raise err File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection sock.connect(sa) TimeoutError: [Errno 110] Connection timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen httplib_response = self._make_request( File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request self._validate_conn(conn) File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn conn.connect() File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect self.sock = conn = self._new_conn() File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f33c0792cd0>: Failed to establish a new connection: [Errno 110] Connection timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/requests/adapters.py", line 486, in send resp = conn.urlopen( File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen retries = retries.increment( File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bennyguo/zero123-xl-diffusers (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f33c0792cd0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "main.py", line 901, in gui.train(opt.iters) File "main.py", line 875, in train self.prepare_train() File "main.py", line 145, in prepare_train self.guidance_zero123 = Zero123(self.device) File "/home/lancer/dreamgaussian/guidance/zero123_utils.py", line 29, in **init** self.pipe = Zero123Pipeline.from_pretrained( File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 939, in from_pretrained cached_folder = cls.download( File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 1441, in download info = model_info( File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn return fn(*args, **kwargs) File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 1697, in model_info r = get_session().get(path, headers=headers, timeout=timeout, params=params) File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/requests/sessions.py", line 602, in get return self.request("GET", url, **kwargs) File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 63, in send return super().send(request, *args, **kwargs) File "/home/lancer/anaconda3/envs/dreamgaussian/lib/python3.8/site-packages/requests/adapters.py", line 519, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bennyguo/zero123-xl-diffusers (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f33c0792cd0>: Failed to establish a new connection: [Errno 110] Connection timed out'))"), '(Request ID: ac1df403-7df9-489f-b9c9-7f9d7ad8cd24)') `
> 
> Can I git zero123 to the specified folder myself to solve this problem?

Hey! I met the same problem and cannot solve it. I wonder if you solved the problem and could provide some suggestions.
