### ISSUE TITLE
PyMeshlab and Gradio errors

### ISSUE THREAD

**Issue by v4r4rth** [dreamgaussian/dreamgaussian#96]
Facing the following problem:

> Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://c4520b46a45de4ebb9.gradio.live
This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
python process.py tmp_data/tmp.png
/usr/local/lib/python3.8/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
EP Error /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1193 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libnvinfer.so.8: cannot open shared object file: No such file or directory
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'AzureExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
[INFO] loading image tmp_data/tmp.png...
[INFO] background removal...
[INFO] recenter...
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from gs_renderer import Renderer, MiniCam
  File "/root/dreamgaussian/gs_renderer.py", line 18, in <module>
    from mesh_utils import decimate_mesh, clean_mesh
  File "/root/dreamgaussian/mesh_utils.py", line 2, in <module>
    import pymeshlab as pml
  File "/usr/local/lib/python3.8/dist-packages/pymeshlab/__init__.py", line 11, in <module>
    from .pmeshlab import *
ModuleNotFoundError: No module named 'pymeshlab.pmeshlab'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1559, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1447, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.8/dist-packages/gradio/components/model3d.py", line 172, in postprocess
    "name": self.make_temp_copy_if_needed(y),
  File "/usr/local/lib/python3.8/dist-packages/gradio/components/base.py", line 233, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/usr/local/lib/python3.8/dist-packages/gradio/components/base.py", line 197, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/tmp_mesh.glb'

Please suggest how I can fix this

**Comment by Zenodia** [comment]
encounter same problem, please address this issue
