### ISSUE TITLE
I got error

### ISSUE THREAD

**Issue by altava-sgp** [dreamgaussian/dreamgaussian#98]
This is log
```shell
# python3 main.py --config configs/image.yaml input=data/test_rgba.png save_path=test_rgba
[INFO] load image from data/test_rgba.png...
Number of points at initialisation :  5000
[INFO] loading zero123...
Keyword arguments {'trust_remote_code': True} are not expected by Zero123Pipeline and will be ignored.
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 34.00it/s]
[INFO] loaded zero123!
100%|███████████████████████████████████████████████████████████████████████████████████████████| 500/500 [12:55<00:00,  1.55s/it]
[INFO] save model to logs/test_rgba_model.ply.
Traceback (most recent call last):
  File "/root/github/dreamgaussian/main.py", line 905, in <module>
    gui.train(opt.iters)
  File "/root/github/dreamgaussian/main.py", line 886, in train
    self.save_model(mode='geo+tex')
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/github/dreamgaussian/main.py", line 402, in save_model
    mesh = self.renderer.gaussians.extract_mesh(path, self.opt.density_thresh)
  File "/root/github/dreamgaussian/gs_renderer.py", line 300, in extract_mesh
    occ = self.extract_fields(resolution).detach().cpu().numpy()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/github/dreamgaussian/gs_renderer.py", line 237, in extract_fields
    mn, mx = xyzs.amin(0), xyzs.amax(0)
IndexError: amin(): Expected reduction dim 0 to have non-zero size.
```

**Comment by chy2013920202** [comment]
The iters in the YAML file you are using (such as image. yaml) need to be a multiple of 100, not in the form of 650.
